spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  application:
    name: config-client #为服务名称
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
--- 
server:
  port: 8204
spring:
  application:
    name: config-client #为服务名称
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
